apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-application
  namespace: backend-namespace
  labels:
    app: backendApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendApp
  template:
    metadata:
      labels:
        app: backendApp
    spec:
      containers:
        - name: myAPP
          image: mustafaessam/backendsimpleapp:v55
          ports:
            - containerPort: 3000
              protocol: TCP
