pipeline {
    agent any
    parameters {
        choice(name: 'ENV', choices: ['dev', 'test', 'prod',"release"])
    } 
    stages {
        stage('build') {
            steps {
                echo 'build'
                script{
                    if (params.ENV == "release") {
                        withCredentials([usernamePassword(credentialsId: 'DockerHub-Account', usernameVariable: 'MustafaEssam', passwordVariable: 'DockerHub123456')]) {
                            sh '''
                                docker login -u ${MustafaEssam} -p ${DockerHub123456}
                                docker build -t kareemelkasaby/bakehouseitismart:v${BUILD_NUMBER} .
                                docker push kareemelkasaby/bakehouseitismart:v${BUILD_NUMBER}
                                echo ${BUILD_NUMBER} > ../build.txt
                            '''
                        }
                    }
                    else {
                        echo "user choosed ${params.ENV}"
                    }
                }
            }
        }
        stage('deploy') {
            steps {
                echo 'deploy'
                script {
                    if (params.ENV == "dev" || params.ENV == "test" || params.ENV == "prod") {
                        withCredentials([file(credentialsId: 'slave-kubeconfige', variable: 'KUBECONFIG_To_Slave')]) {
                            sh '''
                                export BUILD_NUMBER=$(cat ../build.txt)
                                mv Deployment/deploy.yaml Deployment/deploy.yaml.tmp
                                cat Deployment/deploy.yaml.tmp | envsubst > Deployment/deploy.yaml
                                rm -f Deployment/deploy.yaml.tmp
                                kubectl apply -f Deployment --kubeconfig ${KUBECONFIG_To_Slave} -n ${ENV}
                            '''
                        }
                    }
                }
            }
        }

        stage("Display"){
            steps{
                echo "============= Displaying choices . . . "
                
                script{
                     def choicesd = ['1] dev', '2] test', '3] prod',"4] release"]
                     for (ans in choicesd){
                            echo "${ans}"
                     }
                }
            }
        }

    }
}
